### ISSUE TITLE
Documentation error for lifecyle hook ignore changes

### ISSUE THREAD

**Issue by rancid-racer** [hashicorp/terraform-website#1030]
Link: https://www.terraform.io/docs/configuration/resources.html#ignore_changes

Documentation clearly indicates that the resource is not in quotes and that there is a comma placed after the item in the list.  Please indicate that the item should be in quotes and that the comma is not supposed to be there unless there is multiple items ( as expected in a typical list. )

**Comment by bflad** [comment]
Hi @rancid-racer 👋  Thank you for raising this.

Since this issue was introduced, there have been a number of changes to that documentation, which now lives here: https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes

I believe recent versions of Terraform CLI provide configuration feedback if these `lifecycle` `ignore_changes` list items are enclosed in quotes when they should not be. The maintainers of that codebase would need to elaborate more specifically on that particular decision as compared to other list configurations, but the configuration present on the current page has the expected syntax.

Allowing trailing commas in lists, sets, or tuples is more a design feature of HashiCorp Configuration Language (HCL), which underpins Terraform's configuration language. Including or omitting trailing commas is formatting choice where either is correct. Some folks prefer trailing commas to reduce cognitive load or unnecessary VCS line changes when adding or removing elements. The example is currently using a multiple line list with a trailing comma, which seems appropriate in that situation for the reasons just mentioned.

If you have a specific documentation request, please file a new issue over in the [Terraform CLI repository](https://github.com/hashicorp/terraform/issues) so the maintainers can triage. If you have more general questions about this functionality or its configuration, please feel free to submit a new discussion thread in the [Terraform CLI section of the HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
