### ISSUE TITLE
cannot use testAccProvider (variable of type *schema.Provider) as terraform.ResourceProvider value in map literal: wrong type for method Apply

### ISSUE THREAD

**Issue by joel-g** [hashicorp/terraform-website#1038]
When following the below example copied from [this document](https://www.terraform.io/docs/extend/testing/acceptance-tests/testcase.html) I get a type error on `testAccProvider` : 

```
cannot use testAccProvider (variable of type *schema.Provider) as terraform.ResourceProvider value in map literal: wrong type for method Apply
```

```
// File: example/provider_test.go
package example

var testAccProviders map[string]terraform.ResourceProvider
var testAccProvider *schema.Provider

func init() {
  testAccProvider = Provider().(*schema.Provider)
  testAccProviders = map[string]terraform.ResourceProvider{
    "example": testAccProvider,
  }
}
```

**Comment by fabstu** [comment]
Try to use `github.com/hashicorp/terraform-plugin-sdk/terraform` instead of `github.com/hashicorp/terraform`.

**Comment by bflad** [comment]
Hi @joel-g 👋  Thank you for raising this and apologies it was lingering for so long. 

Given the age of this issue, the suggestion by @fabstu above was likely on the right track for when the Terraform Plugin SDK codebase was split from the main Terraform CLI repository. Otherwise a really good resource for getting started with a provider development and acceptance testing can be found in the template repository https://github.com/hashicorp/terraform-provider-scaffolding which has end to end example code available.

If you have further questions, it might be best to raise them in the [HashiCorp Discuss Forums category for the Terraform Plugin SDK](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43), which is monitored by the Terraform Plugin SDK team and other provider developers whereas this repository is generally only monitored by documentation-focused teams.
