### ISSUE TITLE
AWS EKS Introduction is incorrect

### ISSUE THREAD

**Issue by cthulhua** [hashicorp/terraform-website#1061]
The [learn.hashicorp.com AWS EKS intro](https://learn.hashicorp.com/terraform/aws/eks-intro) has incorrect IAM roles.

From the [Worker Node IAM Role and Instance Profile section](https://learn.hashicorp.com/terraform/aws/eks-intro#worker-node-iam-role-and-instance-profile)
```
resource "aws_iam_role" "demo-cluster" {
  name = "terraform-eks-demo-cluster"

 ...
}

resource "aws_iam_role_policy_attachment" "demo-cluster-AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.demo-node.name
}

resource "aws_iam_role_policy_attachment" "demo-cluster-AmazonEKSServicePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
  role       = aws_iam_role.demo-node.name
}
```

Note that the aws_iam_role name "demo-cluster" does not match the policy_attachments, which refer to "demo-node". The Cluster IAM role is similarly wrong. 

This issue does not seem to be present in the example repo - https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started.

I'm posting this here, because I saw this issue, https://github.com/hashicorp/terraform-website/issues/806
in which it's mentioned that this is the right place to report learn.hashicorp.com issues.

**Comment by bflad** [comment]
Hi @cthulhua 👋  Thank you for raising this.

The Terraform configuration associated with this tutorial was made public at some point since this was filed. 🎉  https://github.com/hashicorp/learn-terraform-provision-eks-cluster which uses https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

Taking a brief look, this issue is not present in those configurations. If you have any additional feedback, please file a new issue over in that repository. Thanks so much.
