### ISSUE TITLE
Third-party Plugins Windows location

### ISSUE THREAD

**Issue by RichieRunner** [hashicorp/terraform-website#108]
https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

> On Windows, in the sub-path terraform.d/plugins beneath your user's "Application Data" directory. 

Shouldn't it specifically be "Roaming"  under Application Data?

I would create PR, but could not find the MD doc for this page.

**Comment by nfagerlund** [comment]
I just went searching for more on this, and it looks like the answer is Windows-version dependent:

* It's always in the `%APPDATA%` folder, whatever that happens to be. 
* In older Windows versions that was just the application data directory.
* Nowadays `%APPDATA%` that "Roaming" subdir.

So, let's just rewrite all instances of this to use the `%APPDATA%` variable instead of that generic placeholder.

**Comment by nfagerlund** [comment]
eventually resolved as https://github.com/hashicorp/terraform-website/pull/565
