### ISSUE TITLE
Build failures - Remote file does not exist -- broken link!!!

### ISSUE THREAD

**Issue by abitrolly** [hashicorp/terraform-website#1243]
I see that all recent builds fail with the same error:
```
unlink: No such file or directory
2020-05-06 23:16:42 URL:http://127.0.0.1:4567/docs/providers/openstack/ [78938/78938] -> "index.html.tmp.tmp" [1]
http://127.0.0.1:4567/api/:
Remote file does not exist -- broken link!!!
Found 2 broken links.

http://127.0.0.1:4567/api/
http://127.0.0.1:4567/docs/providers/turbot/r/garnt_activation.html

FINISHED --2020-05-06 23:16:42--
Total wall clock time: 3m 51s
Downloaded: 6691 files, 563M in 0.8s (725 MB/s)
make: *** [website-test] Error 8
The command "make website-test" exited with 2.
```

https://travis-ci.org/github/hashicorp/terraform-website/builds/684050441#L9247

What is causing this?

**Comment by nfagerlund** [comment]
It's a broken link in one of the providers. I'll deal with it after running down a few more pull requests.

**Comment by abitrolly** [comment]
@nfagerlund is it possible to specifically show where the link is located?

**Comment by nfagerlund** [comment]
Due to the link checker being extremely primitive, no, it is not. But there's [an extensive writeup in the readme about broken link detective work](https://github.com/hashicorp/terraform-website/#finding-broken-links), and: 

- The link in the turbot provider is probably an issue in the turbot provider's repo. 
- The /api/ one is characteristic of something that the Oracle people reliable screw up every couple of weeks.

**Comment by abitrolly** [comment]
I wonder if something like https://github.com/urlstechie/urlchecker-python will work better.

**Comment by nfagerlund** [comment]
Quite likely; we're replacing the entire platform that builds this website later this year (with something roughly equivalent but more performant and featureful), and we'll want to integrate something that works well with that rather than building tooling for the current doomed platform. 

In the meantime, I've filed PRs to deal with the current batch of broken links, so I'm going to close this issue for the time being. Thanks for reporting! 

https://github.com/terraform-providers/terraform-provider-turbot/pull/6
https://github.com/terraform-providers/terraform-provider-oci/pull/1054
