### ISSUE TITLE
unable to merge PRs due to broken link issue 

### ISSUE THREAD

**Issue by nahuel242** [hashicorp/terraform-website#1268]
I was filing the PR https://github.com/hashicorp/terraform-website/pull/1267 to the terraform docs and when I created  it and the CI kicked in it failed with the following error:

```
http://127.0.0.1:4567/docs/providers/avi/r/avi_useraccount.html:
Remote file does not exist -- broken link!!!
```
I went to to the avi provider repo to fix the issue and I found [this PR ](https://github.com/terraform-providers/terraform-provider-avi/pull/61) merged 6 days ago fixing it.

When I checked the logs for the failed job I found in the [line 892](https://travis-ci.org/github/hashicorp/terraform-website/jobs/689392530#L892) it was checking out the commit https://github.com/terraform-providers/terraform-provider-avi/commit/1ec1d4de167fe29c425e9b987f0e8199343ebed2 to run the tests,  which it's older than the fixed version and I think that's why all the builds from the terraform-website are failing

**Comment by bflad** [comment]
Phew, this issue was left lingering, sorry about that, @nahuel242! A lot of things have changed with this repository since this was filed, including the removal of submodules (and subsequent link checking) for verified provider documentation since these providers are now documented on the Terraform Registry. I believe this solution covers the intent of this issue as provider link checking is no longer relevant, but if there are still specific items you would like addressed with the current website codebase please reach out in a new issue. 👍
