### ISSUE TITLE
Add navigation from registry to terraform.io

### ISSUE THREAD

**Issue by robbruce** [hashicorp/terraform-website#1339]
I have noticed that some providers documentation redirect to the corresponding documentation on registry.terraform.io. For example

https://www.terraform.io/docs/providers/random/index.html
redirects to
https://registry.terraform.io/providers/hashicorp/random/latest/docs

However, when using the documentation sometimes you may need to check the configuration language (for functions, expressions etc).

Yes, there is a back button, but you could be clicking back a lot just if you have navigated around a provider. Just having a link to terraform docs would be useful.

**Comment by laurapacilio** [comment]
Hi,

Thank you for the suggestion! Since you submitted this issue, a few things have happened:
1. All documentation for all providers is hosted on the Terraform Registry. 
2. We've added links from the Terraform Registry back to the documentation site, where appropriate. For example, see the **Helpful Links** section on the right of the random provider docs! It has links back to the documentation site as well as to HashiCorp Learn. 

<img width="959" alt="Screen Shot 2021-07-12 at 5 23 10 PM" src="https://user-images.githubusercontent.com/83350965/125357667-ed5d0400-e335-11eb-9889-828455345acc.png">

I'm going to close this issue, and wanted to let you know how this has been resolved.
