### ISSUE TITLE
Typo in image CLI-How it works

### ISSUE THREAD

**Issue by Florian86** [hashicorp/terraform-website#1504]
Hello,

I just wanted to let you know about a minor spelling mistake in the image `/content/source/assets/images/terraform-overview/cli-howitworks[-1x/2x].png`.

![typo](https://user-images.githubusercontent.com/868508/99148499-45991480-2688-11eb-8805-c02011ff5376.png)

As far as I can tell there is no "source file" for the software used to create it. And trying to fix it on the `.png` file did not make sense to me. That's why I'm just leaving the hint here and hope that's fine.

Greetings

**Comment by laurapacilio** [comment]
Hi @Florian86 thank you for submitting this! I'm sorry about the incredibly delayed response.

I investigated, and the only place I could find this image is in an older version of the terraform.io homepage. We have since reworked that page, and I don't see the image in there anymore. So, I'm going to close out this issue, but please reopen if you still see this somewhere on the site!
