### ISSUE TITLE
writing custom providers documentation should mention golang 1.12 dependency

### ISSUE THREAD

**Issue by bhudlemeyer** [hashicorp/terraform-website#1514]
I am trying to build a new provider plugin and when following the documentation listed here:  https://www.terraform.io/docs/extend/writing-custom-providers.html

```
Terraform v0.12.18

Golang v 1.13.5
```

I get the following GO errors:
```
{
	"resource": "/home/bhudlemeyer/go/src/github.com/bhudlemeyer/terraform-opsman-provider/main.go",
	"owner": "go",
	"severity": 8,
	"message": "cannot find package \"github.com/hashicorp/terraform-plugin-sdk/terraform\" in any of:\n\t/usr/lib/go-1.13/src/github.com/hashicorp/terraform-plugin-sdk/terraform (from $GOROOT)\n\t/home/bhudlemeyer/go/src/github.com/hashicorp/terraform-plugin-sdk/terraform (from $GOPATH)",
	"source": "go",
	"startLineNumber": 5,
	"startColumn": 2,
	"endLineNumber": 5,
	"endColumn": 55
}

{
	"resource": "/home/bhudlemeyer/go/src/github.com/bhudlemeyer/terraform-opsman-provider/main.go",
	"owner": "go",
	"severity": 8,
	"message": "cannot find package \"github.com/hashicorp/terraform-plugin-sdk/plugin\" in any of:\n\t/usr/lib/go-1.13/src/github.com/hashicorp/terraform-plugin-sdk/plugin (from $GOROOT)\n\t/home/bhudlemeyer/go/src/github.com/hashicorp/terraform-plugin-sdk/plugin (from $GOPATH)",
	"source": "go",
	"startLineNumber": 4,
	"startColumn": 2,
	"endLineNumber": 4,
	"endColumn": 52
}

{
	"resource": "/home/bhudlemeyer/go/src/github.com/bhudlemeyer/terraform-opsman-provider/provider.go",
	"owner": "go",
	"severity": 8,
	"message": "cannot find package \"github.com/hashicorp/terraform-plugin-sdk/helper/schema\" in any of:\n\t/usr/lib/go-1.13/src/github.com/hashicorp/terraform-plugin-sdk/helper/schema (from $GOROOT)\n\t/home/bhudlemeyer/go/src/github.com/hashicorp/terraform-plugin-sdk/helper/schema (from $GOPATH)",
	"source": "go",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 2
}

```

Having googled around some more to see if I could figure out why this was happening I stumbled across 

[Issue 22748](https://github.com/hashicorp/terraform/issues/22748)

Looking at the git hub repo I found that Terraform is still locked to 1.12.x it appears. 

My main issue with this is the documentation on [custom Provider](https://www.terraform.io/docs/extend/writing-custom-providers.html) doesn't mention this at all. Can the documentation be updated to list this limitation? As for a first time user (and honestly a bit of a novice to golang) it took a while to track down what was causing my issue. 

In case it matters current golang env info:
```
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bhudlemeyer/.cache/go-build"
GOENV="/home/bhudlemeyer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bhudlemeyer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build590174508=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bflad** [comment]
Hi folks 👋 

There has been a lot of changes to provider development and its documentation since this issue was originally introduced. For example, the page referenced here has been migrated to an entire section of tutorials on the HashiCorp Learn platform (https://learn.hashicorp.com/collections/terraform/providers) and there is a template repository available to jumpstart a Terraform Provider codebase (https://github.com/hashicorp/terraform-provider-scaffolding). Recent versions of the Go language automatically enable or require modules for development, which likely also alleviate some of the original problems of when that functionality was still being developed in the Go language ecosystem.

If you believe there is still an issue to address with the documentation, please create a new issue and we can take a fresh look. Otherwise, if you are looking for general assistance Terraform Provider development, the [Terraform Plugin SDK section of the HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) is likely the best place to followup as that is monitored by the teams responsible for that development experience along with other provider developers. 👍
