### ISSUE TITLE
Request: "FQN" Missing in Glossary

### ISSUE THREAD

**Issue by rrrix** [hashicorp/terraform-website#1631]
I've noticed the term "FQN" mentioned (occasionally) officially and (quite often) unofficially around in the community, in source code, on StackOverflow, community forums, etc.

Googling' `terraform "fqn"`, it appears it means "fully qualified name" but I'm still not _exactly_ sure what that means in the context of Terraform and writing Terraform config files in HCL, using the Terraform CLI, and working with Providers, Modules and the ecosystem at large. 

The best I've come across is a thread in the Terraform repo: https://github.com/hashicorp/terraform/issues/25172#issuecomment-641348089 

It would be greatly appreciated to have `FQN` in the official glossary to shine some light on this acronym.

**Comment by laurapacilio** [comment]
Thank you for submitting this request!

I did some investigation, and found that we have this [section in the docs about provider "source addresses,"](https://www.terraform.io/docs/language/providers/requirements.html#source-addresses) which is our formal name for what you're referring to in the context of providers. It actually has a lot of the information in that ticket thread you found, which is great! And it mentions the creation of a "fully-qualified address," (AKA a fully-qualified name). 

It appears that Fully-Qualified Name is kind of a general [industry term](https://en.wikipedia.org/wiki/Fully_qualified_name#) 
to describe "an unambiguous nam," and it's not specific to Terraform. I think that's why folks use it informally to refer to the unique identifiers Terraform constructs to refer to providers, etc. on the backend. I've also seen it used in other doc sets. But because it's not Terraform-specific and it's not an official Terraform term, we're going to avoid adding FQN to the Terraform glossary. But, we still appreciate the suggestion  :-)

One possible option is to add "source address" to the glossary and explain what that is for folks. Let me know if you think that would be helpful!

**Comment by laurapacilio** [comment]
Going to close this out, given that we've explained our rationale above. Please reopen if needed!
