### ISSUE TITLE
Port 32846's  intent is not clear in document

### ISSUE THREAD

**Issue by ausmartway** [hashicorp/terraform-website#1716]
The intended usage of port 32846 is not clear from the document.

The document says "* **32846:** TFE admin console (a Replicated service)" but the explanation is not clear.

https://github.com/hashicorp/terraform-website/pull/1275 indicates this change is based on support ticket 28893, but the support bundle show it is a connection from local machine , instead of from Adiministrator.

I suggest we remove this port from the document if it is a mistake, or clearly document the intent of this port.

**Comment by laurapacilio** [comment]
Hello! The [Network Requirements for Terraform Enterprise](https://www.terraform.io/docs/enterprise/before-installing/network-requirements.html) page does not contain any more mention of 32846 on that page. I'm assuming that this has been corrected since you opened this ticket (sorry for the delay in responding!). So, I'm going to close this out, but please feel free to reopen if needed!
