### ISSUE TITLE
Something has been broken/changed in the CI since the 15th of December

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform-website#2023]
Hi!

I am not sure completely what has changed starting from 57c0c40b7e71d17f03c9067c9f469398dc1da360 but https://github.com/antonbabenko/terraform-docs-as-pdf relies on the structure of this repository and that broke my builds, too.

https://github.com/antonbabenko/terraform-docs-as-pdf/issues/5

I would prefer to have this issue open until CI is fixed in this repo so that I can look into it and reapply similar changes into my repo.

Thanks,
Anton.

**Comment by sudomateo** [comment]
A migration was performed this past week. You can read about in [here](https://github.com/hashicorp/terraform-website/blob/master/MIGRATION.md).

As part of that migration, the locally built website does not listen on port 4567 anymore but rather on port 3000. You can see that [here](https://github.com/hashicorp/terraform-website/blob/1e5abd1f62cdc0fcd78484c36ed4873b805f3c80/Makefile#L13). After a brief look at your code, I noticed that you are still using the old port [here](https://github.com/antonbabenko/terraform-docs-as-pdf/blob/master/bin/generate.sh#L3).

I tried to execute the workflow defined in your repository, but I was unable to execute the `wkhtmltopdf` tool due to the following error on my machine:

```
Error: This version of wkhtmltopdf is built against an unpatched version of QT, and does not support more than one input document.
```

I also took a brief look at your failing CI/CD process and noticed the following error:

```
Unable to find current origin/master revision in submodule path 'ext/terraform'
```

Both the `ext/terraform` and `ext/terraform-cdk` Git submodules do not have an `origin/master` revision (they switched to using `main` instead of master some time ago).

Regardless, in my opinion this issue should be closed and the source of truth issue should be https://github.com/antonbabenko/terraform-docs-as-pdf/issues/5 since the issue is a now broken PDF generation process on your repository rather than failing CI/CD process on this repository.

**Comment by antonbabenko** [comment]
Thanks a lot for such a detailed answer!

I have to admit that I didn't do deep research on what has changed recently in this repository as soon as I discovered that CI here is red, too.

Have a great day!
