### ISSUE TITLE
Resource page 'aws_iam_user_group_membership' mistake

### ISSUE THREAD

**Issue by Cybernisk** [hashicorp/terraform-website#272]
Mistake on ['aws_iam_user_group_membership'](https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html) page.
There is no `resource` name in example section.

**Source:**

> resource "aws_iam_user_group_membership" {
  user = "${aws_iam_user.user1.name}"
  groups = [
    "${aws_iam_group.group1.name}",
    "${aws_iam_group.group2.name}",
  ]
}

>resource "aws_iam_user_group_membership" {
  user = "${aws_iam_user.user1.name}"
  groups = [
    "${aws_iam_group.group3.name}",
  ]
}

**Change to:**

> resource "aws_iam_user_group_membership" "attach-user-groups-1" {
  user = "${aws_iam_user.user1.name}"
  groups = [
    "${aws_iam_group.group1.name}",
    "${aws_iam_group.group2.name}",
  ]
}

>resource "aws_iam_user_group_membership" "attach-user-groups-2" {
  user = "${aws_iam_user.user1.name}"
  groups = [
    "${aws_iam_group.group3.name}",
  ]
}

**Comment by bflad** [comment]
Hi @Cybernisk! 👋 Thanks so much for submitting this. Any of the resource specific documentation actually comes from the provider repositories themselves, so in this case: https://github.com/terraform-providers/terraform-provider-aws

This was fixed with https://github.com/terraform-providers/terraform-provider-aws/pull/4686 👍
