### ISSUE TITLE
NoMethodError at /docs/index.html undefined method `force_encoding' for nil:NilClass

### ISSUE THREAD

**Issue by jlsuttles** [hashicorp/terraform-website#3]
I ran `make website`, visited http://localhost:4567, and clicked on the "Docs" link.

<img width="663" alt="screen shot 2017-06-27 at 11 03 37 am" src="https://user-images.githubusercontent.com/95995/27602720-97b6a34c-5b28-11e7-9792-456b5906d9bc.png">

```
NoMethodError: undefined method `force_encoding' for nil:NilClass
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:289:in `ensure in binary'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:289:in `binary'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:279:in `extract_magic_comment'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:275:in `extract_encoding'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:191:in `precompiled'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/erb.rb:57:in `precompiled'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/erb.rb:104:in `precompiled'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:245:in `compile_template_method'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:240:in `compiled_method'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:169:in `evaluate'
	/usr/local/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/rendering.rb:313:in `render_individual_file'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/rendering.rb:153:in `render_template'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
	/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/util.rb:41:in `instrument'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:244:in `instrument'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/sitemap/resource.rb:100:in `render'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:209:in `catch'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:209:in `call!'
	/usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:195:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
	/usr/local/bundle/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
	/usr/local/bundle/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/showexceptions.rb:24:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/lint.rb:49:in `_call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/lint.rb:37:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'
	/usr/local/bundle/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
	/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by apparentlymart** [comment]
Sorry this isn't working properly, @jlsuttles :confused: 

This looks like the same problem being discussed in middleman/middleman#1536. If I'm understanding correctly, this was eventually blamed on some issues with case-insensitive filenames on Mac OS, but since we have all the same filenames we had before and indeed the symptoms are _slightly_ different here I think a similar but different problem applies here.

Are you using Docker for Mac there? The big difference between this new website setup and the old is that it uses symlinks to connect the docs from the various repository submodules, so my guess is that the extra `osxfs` layer that is used for volumes on OS X is having some trouble with how the symlinks are set up.

Unfortunately I don't have a Mac handy to try this on right now but I'll see if I can get hold of one tomorrow to try to repro this and dig in some more.

In the mean time, it _might_ work to run `make build` to produce a static copy of the website in the subdir `build`, or assuming you're working on TFE docs you can probably access directly the URL http://127.0.0.1:4567/docs/enterprise/index.html, which (if my theory is correct) should work correctly since no symlinks need to be traversed to deal with this part of the site.

**Comment by jlsuttles** [comment]
@apparentlymart Thanks for looking into this! I am using Docker for Mac. It is not blocking me, so I will close the issue. I just wanted to make sure it wasn't going to be an issue when deploying the docs!

**Comment by vancluever** [comment]
Just FYI - this is something very similar to what I've been running into as well on my Linux box. If it isn't fixed by that time I will dive in after I'm done with an AWS provider PR I've been working on!

**Comment by apparentlymart** [comment]
Thanks @vancluever. @grubernaut also reproed on Linux earlier, so seems like my theory was wrong. I'm trying to get a repro on my machine here.

**Comment by gberche-orange** [comment]
@vancluever @apparentlymart I'm reproducing on a Linux box (running in a virtual box), as part of https://github.com/mevansam/terraform-provider-cf/pull/142#issuecomment-423928615 

Not sure if this could be related but in http://127.0.0.1:4567/__middleman/config/ I have
> :encoding = "utf-8"
> Default string encoding for templates and output

**Comment by imjoey** [comment]
hi @apparentlymart , I also encountered the same issue on my local Docker for Mac when accessing `/docs/index.html`. Currently I'm working the [terraform provider for oVirt](https://github.com/imjoey/terraform-provider-ovirt), this issue probably blocks me due to failed to access all of the ovirt provider related pages, with the error of `File Not Found`. Any thoughts on this? Great thanks.

**Comment by jereksel** [comment]
I have it on "/downloads.html" on Hyper-V'd Ubuntu 20.04
