### ISSUE TITLE
terraform-website/content/source/docs/extend/resources.html.md needs type clarification

### ISSUE THREAD

**Issue by jalvarezferr** [hashicorp/terraform-website#647]
The terraform-website/content/source/docs/extend/resources.html.md page includes state migration examples, where migration functions include a parameter "inst *terraform.InstanceState. It is unclear (to me at least), what type is passed by terraform to this function in the case of a custom provider, as the one in the sample code is specific to the given example.
Sorry if this should should be clear to me, but after digging the docs and the code, could not find it.

**Comment by bflad** [comment]
Hi @jalvarezferr 👋  Thank you for raising this and sorry this was left lingering.

The updated provider documentation page for this concept can be found here: https://www.terraform.io/docs/extend/resources/state-migration.html

Since this issue was raised, Terraform CLI 0.12 (and many more versions now) was released which require state migrations in the `StateUpgraders` format. The documentation linked above goes into an example of how to perform those upgrades as necessary, but the key part is that it no longer depends on the previously shared Go type. 

We don't anticipate further usage of the Terraform CLI 0.11 and prior `MigrateState` functionality given that Terraform CLI 0.12 has been released for awhile now. Due to that, and since the `MigrateState` functionality may be removed from the documentation to prevent confusion, I'm going to close this out. If you are looking for the Go documentation for the `terraform.InstanceState` type in the current SDK, it can be found here: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/terraform#InstanceState 👍
