### ISSUE TITLE
About completely separating the website project

### ISSUE THREAD

**Issue by moreal** [hashicorp/terraform-website#715]
Now, `terraform-website` project has so many submodules from `terraform`  
So, the project has not been completely separated.

In my thought, they have to focus on their jobs like `implements terraform-cli`, `make website`, etc...

So I suggest this.

**Comment by moreal** [comment]
Is there no one working for this? :(

**Comment by nfagerlund** [comment]
Hello,

We currently don't want to completely separate the website project — most documentation updates come from the engineering teams, and keeping the docs in a convenient place for them means better docs. We pay a cost, but we also get a benefit. 

I know it can be disorienting to work in this repo, and we recently [rewrote the README here](https://github.com/hashicorp/terraform-website/blob/master/README.md) to make it more helpful. I hope that helps somewhat! 

We are also thinking hard about the future of provider documentation right now; we haven't finished our plans, but it's very likely that the providers will not be submodules in this repo in a year and a half. So that might help somewhat too.
