### ISSUE TITLE
Missing mention of `Exists` schema in Writing Custom Providers Guide

### ISSUE THREAD

**Issue by splashx** [hashicorp/terraform-website#907]
There is no mention of the schema `Exists` in the [providers guide](https://www.terraform.io/docs/extend/writing-custom-providers.html).

* It could be mentioned in [Implementing Read](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-read) as an alternative to `d.SetId("")`.

* It could be mentioned in the [Defining Resources](https://www.terraform.io/docs/extend/writing-custom-providers.html#defining-resources)

etc.

**Comment by bflad** [comment]
Hi @splashx 👋  Thank you for writing this in.

The choice to omit `Exists` for provider development with Terraform Plugin SDK, especially in version 2 of that framework, is due to the often repetitive code it introduced which led to its deprecation. `Exists` was a SDK-only implementation detail which often caused developers to implement nearly duplicate code to `Read`, just with a boolean return value and not usable data that could be then used to set state information for code reuse.

Since this field and functionality is deprecated, I'm going to close this out.

For more information about this field and its deprecation, please refer to https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource.Exists

```
	// Exists is a function that is called to check if a resource still
	// exists. If this returns false, then this will affect the diff
	// accordingly. If this function isn't set, it will not be called. You
	// can also signal existence in the Read method by calling d.SetId("")
	// if the Resource is no longer present and should be removed from state.
	// The *ResourceData passed to Exists should _not_ be modified.
	//
	// Deprecated: ReadContext should be able to encapsulate the logic of Exists
	Exists ExistsFunc
```
