### ISSUE TITLE
"Implementing a more complex Read" session in "Writing Custom Providers" mentions closed issue

### ISSUE THREAD

**Issue by splashx** [hashicorp/terraform-website#908]
The [guide mentions](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-a-more-complex-read):
> Due to the limitation of tf-11115 it is not possible to nest maps. 

But [tf-11115 has been closed](https://github.com/hashicorp/terraform/issues/11115) - so it's not clear if the limitation still exists.

**Comment by wwboynton** [comment]
Glad to see someone else has acknowledged this before me. Hey @apparentlymart, it seems like @pdecat [initially made a PR from a fork](https://github.com/hashicorp/terraform-website/pull/938) to resolve this but then closed it without merging, based on the assertion that _"cleaning that part is more complex than that."_

Within the next few days or weeks I will probably have to write a provider, so I guess I can try nesting some maps and see what happens, but in the meantime it would probably be good to get some eyes on this since it seems like the documentation _might_ be leading new contributors to believe that they must work around a limitation which has been [resolved for more than a year](https://github.com/hashicorp/terraform/issues/11115#issuecomment-440092246).

**Comment by apparentlymart** [comment]
Hi all,

Terraform Core v0.12 and later supports maps of any type, but the current Terraform SDK still speaks the old protocol (via a translation layer) and so this limitation is still present from a provider development standpoint.

I don't see an issue directly about nested maps but the plugin SDK repository already has some issues about exposing the new Terraform v0.12 type system to providers and so I expect in the end this category of limitations would all be resolved together:

* hashicorp/terraform-plugin-sdk#62
* hashicorp/terraform-plugin-sdk#155

The "Writing Custom Providers" section is architecturally attached to the SDK, legacy repository organization details aside, so I expect opening issues about the provider development documentation in [the SDK repository](https://github.com/hashicorp/terraform-plugin-sdk) will make them more visible to the folks who would be primarily responsible for addressing them.

**Comment by laurapacilio** [comment]
The Writing Custom Providers tutorial has since been revamped on HashiCorp Learn, and I believe this is no longer an issue, so I'm going to close. Thanks for flagging!
